name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'  # 仅匹配以 v 开头的标签

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get tag name
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Debug tag
      run: |
        echo "GITHUB_REF is ${GITHUB_REF}"
        echo "TAG is ${TAG}"

    - name: Verify tag
      run: |
        if [[ -z "${{ env.TAG }}" ]]; then
          echo "❌ ERROR: TAG is empty! Check your tag push."
          exit 1
        fi
        echo "✅ TAG is set: ${{ env.TAG }}"

    - name: Show tag name
      run: |
        echo "Building Docker image for tag: ${{ env.TAG }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Show Docker image name before pushing
      run: |
        echo "Docker Image Names:"
        echo "${{ secrets.DOCKER_USERNAME }}/zt-sdmonitor:${{ env.TAG }}"
        echo "${{ secrets.DOCKER_USERNAME }}/zt-sdmonitor:latest"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/zt-sdmonitor:${{ env.TAG }}
          ${{ secrets.DOCKER_USERNAME }}/zt-sdmonitor:latest
